### ISSUE TITLE
Retrain model with more classes

### ISSUE THREAD

**Issue by dimaxano** [marvis/pytorch-yolo2#22]
Hi! I trained model with `n` classes. And then I decided to add `k` classes and to train model on `n+k` classes. Is it possible to use weights from model trained on `n` for model with `n+k` classes?

**Comment by marvis** [comment]
you can use partial.py command to extract the weights you want.

**Comment by jacktkk** [comment]
First of all , thanks for your brilliant work !
There is a little problem troubles me. I know the Pascal VOC datasets has 20 num_classes.
And I wonder why should we create the new module weights like "python partial.py cfg/darknet19_448.cfg darknet19_448.weights darknet19_448.conv.23 23"
Why should we set the cutoff=23 rather than 20 ?
Or maybe I misunderstood the meaning of "cutoff"
Thanks for your reply!
@marvis
@dimaxano
